# Generated by Django 5.0.6 on 2024-06-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="budget_limit",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="expense",
            name="quantity",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profession",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Employee", "Employee"),
                    ("Other", "Other"),
                ],
                default="null",
                max_length=10,
            ),
        ),
    ]
